#!/bin/bash
mkdir Corpus
mkdir Corpus_filtered
mkdir Corpus_filtered/test
mkdir Corpus_filtered/train
mkdir Preprocessed_Corpus_test
mkdir Preprocessed_Corpus_train
mkdir gdep-beta2
mkdir Parsed_output_train
mkdir Parsed_output_test
mkdir Predicted_test_arguements
mkdir Predicted_test_events
mkdir Predicted_test_triggers
mkdir Evaluation/Actual_test_events
mkdir Evaluation/Predicted_test_events
mkdir Evaluation/Prepared_Actual_test_events
mkdir Evaluation/Prepared_Predicted_test_events
